# Generated by Django 6.0.5 on 2026-06-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_name_student_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(blank=True, choices=[('SKG', 'SKG'), ('JKG', 'JKG'), ('Grade IA', 'Grade IA'), ('Grade IB', 'Grade IB'), ('Grade II', 'Grade II'), ('Grade III', 'Grade III'), ('Grade IV', 'Grade IV'), ('Grade V', 'Grade V'), ('Grade VI', 'Grade VI'), ('Grade VII', 'Grade VII'), ('Grade VIII', 'Grade VIII'), ('Grade IX', 'Grade IX')], db_index=True, max_length=10, null=True),
        ),
    ]
